//
// Created by olivier on 24/08/2022.
//

#ifndef INC_2HOL_DEV_MESSAGE_CLIENT_H
#define INC_2HOL_DEV_MESSAGE_CLIENT_H

//TODO: merge this file with message.h
typedef enum messageType {
	SHUTDOWN,
	SERVER_FULL,
	SEQUENCE_NUMBER,
	ACCEPTED,
	NO_LIFE_TOKENS,
	REJECTED,
	MAP_CHUNK,
	MAP_CHANGE,
	PLAYER_UPDATE,
	PLAYER_MOVES_START,
	PLAYER_OUT_OF_RANGE,
	PLAYER_SAYS,
	LOCATION_SAYS,
	PLAYER_EMOT,
	FOOD_CHANGE,
	HEAT_CHANGE,
	LINEAGE,
	CURSED,
	CURSE_TOKEN_CHANGE,
	CURSE_SCORE,
	NAMES,
	APOCALYPSE,
	APOCALYPSE_DONE,
	DYING,
	HEALED,
	MONUMENT_CALL,
	GRAVE,
	GRAVE_MOVE,
	GRAVE_OLD,
	OWNER,
	VALLEY_SPACING,
	FLIGHT_DEST,
	VOG_UPDATE,
	PHOTO_SIGNATURE,
	FORCED_SHUTDOWN,
	GLOBAL_MESSAGE,
	FLIP,
	CRAVING,
	PONG,
	COMPRESSED_MESSAGE,
	UNKNOWN
} messageType;

messageType getMessageType( char *inMessage );//TODO: put this in handler/Message.h

#endif //INC_2HOL_DEV_MESSAGE_CLIENT_H
