//
// Created by olivier on 12/11/2021.
//

#ifndef ONELIFE_GAME_PROCEDURE_GRAPHIC_DRAWPAUSEMODALOBJECT_H
#define ONELIFE_GAME_PROCEDURE_GRAPHIC_DRAWPAUSEMODALOBJECT_H

void drawPauseScreen();


#endif //ONELIFE_GAME_PROCEDURE_GRAPHIC_DRAWPAUSEMODALOBJECT_H
