//
// Created by olivier on 19/12/2021.
//

#ifndef ONELIFE_DATA_VALUE_MESSAGE_H
#define ONELIFE_DATA_VALUE_MESSAGE_H

namespace OneLife::data::value::message
{
	typedef enum
	{
		NONE,
		ACCEPTED,
		BABY_WIGGLE,
		NO_LIFE_TOKENS,
		SEQUENCE_NUMBER,
		SERVER_FULL,
		SHUTDOWN,
		REJECTED,
		MAP_CHUNK,
		MAP_CHANGE,
		PLAYER_UPDATE,
		PLAYER_MOVES_START,
		PLAYER_OUT_OF_RANGE,
		PLAYER_SAYS,
		LOCATION_SAYS,
		PLAYER_EMOT,
		FOOD_CHANGE,
		HEAT_CHANGE,
		LINEAGE,
		CURSED,
		CURSE_TOKEN_CHANGE,
		CURSE_SCORE,
		NAMES,
		APOCALYPSE,
		APOCALYPSE_DONE,
		DYING,
		HEALED,
		MONUMENT_CALL,
		GRAVE,
		GRAVE_MOVE,
		GRAVE_OLD,
		OWNER,
		POSSE_JOIN,
		VALLEY_SPACING,
		FLIGHT_DEST,
		VOG_UPDATE,
		PHOTO_SIGNATURE,
		FORCED_SHUTDOWN,
		GLOBAL_MESSAGE,
		FLIP,
		CRAVING,
		PONG,
		COMPRESSED_MESSAGE,
		FOLLOWING,
		EXILED,
		BAD_BIOMES,
		WAR_REPORT,
		LEARNED_TOOL_REPORT,
		TOOL_EXPERTS,
		TOOL_SLOTS,
		HOMELAND,
		UNKNOWN
	}Type;
}

#endif //ONELIFE_DATA_VALUE_MESSAGE_H
